controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home_list:
    path: [/, /home]
    controller: App\Controller\HomeController::index
cart_list:
    path: [/cart]
    controller: App\Controller\CartController::index
shop_list:
    path: [/shop]
    controller: App\Controller\ShopController::index
shop_add_to_cart:
    path: [/add-to-cart]
    controller: App\Controller\ShopController::addToCart
login_form:
    path: [/login]
    controller: App\Controller\LoginController::login
register_form:
    path: [/register]
    controller: App\Controller\RegisterController::register
logout_form:
    path: [/logout]
    controller: App\Controller\LoginController::logout
add-products:
    path: [/products]
    controller: App\Controller\Products::index
