controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home_list:
    path: [/, /home]
    controller: App\Controller\HomeController::index
cart_list:
    path: [/cart]
    controller: App\Controller\CartController::index
shop_list:
    path: [/shop]
    controller: App\Controller\ShopController::index
login_form:
    path: [/auth]
    controller: App\Controller\LoginController
register_form:
    path: [/register]
    controller: App\Controller\RegisterController
